version: "3.7"

services:
  db:
    container_name: java-pro-postgres-db
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: java-pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

